openapi: 3.0.0
info:
  title: Lunchbunch - Decide your lunch
  version: 1.0.0
servers:
  - url: localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Auth
  - name: Lunch Plan
paths:
  /register:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: sample@gmail.com
                password: hello123
                name: sample
      responses:
        '200':
          description: Successful response
          content:
            application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Request Processed successfully
                status:
                  type: integer
                  example: 200
                success:
                  type: boolean
                  example: true
  /login:
    get:
      tags:
        - Auth
      summary: Login
      responses:
        '200':
          description: Successful response
          content:
            application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Request Processed successfully
                status:
                  type: integer
                  example: 200
                success:
                  type: boolean
                  example: true
  /lunch-plan/:uuid:
    get:
      tags:
        - Lunch Plan
      summary: Get Lunch Plan Detailed
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /lunch-plan:
    get:
      tags:
        - Lunch Plan
      summary: Get List of lunch plans
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Lunch Plan
      summary: Create Lunch Plan
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                date: '2024-10-03'
                description: asdf
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
