version: "3.8"


services:
  lunchbunch-api:
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
    image: lunchbunch-api:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      APP_MYSQL_DB: ${APP_MYSQL_DB}
      APP_MYSQL_HOST: ${APP_MYSQL_HOST}
      APP_MYSQL_PASSWORD: ${APP_MYSQL_PASSWORD}
      APP_MYSQL_USERNAME: ${APP_MYSQL_USERNAME}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXPIRATION: ${APP_JWT_EXPIRATION}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_TOPIC: ${REDIS_TOPIC}
    expose:
      - 8080
  mysql:
    env_file:
      - .env
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE:  ${APP_MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${APP_MYSQL_PASSWORD}
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10