version: "3.8"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lunchbunch
      MYSQL_ROOT_PASSWORD: password
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  lunchbunch-api:
    build:
      dockerfile: Dockerfile
    image: lunchbunch-api:0.0.1
    ports:
      - "8080:8080"  # Replace 8000 with the port exposed by your application
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      APP_MYSQL_DB: lunchbunch
      APP_MYSQL_HOST: mysql
      APP_MYSQL_PASSWORD: password
      APP_MYSQL_USERNAME: root
      APP_JWT_SECRET: VquHiRGQLFPdGSj7V9GmnCamgeOtAXuh
      APP_JWT_EXPIRATION: 86400000
    expose:
      - 8080
  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with eachother internally.
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.11
    container_name: redpanda-0
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s
volumes:
  redpanda-0: {}