spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${APP_MYSQL_HOST}/${APP_MYSQL_DB}
    username: ${APP_MYSQL_USERNAME}
    password: ${APP_MYSQL_PASSWORD}
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  data:
    redis:
      host: redis-19078.c10.us-east-1-3.ec2.cloud.redislabs.com
      port: 19078
      username: default
      password: fx3386n4qleQFbaxfHg59tnykphOrgSv


jwt:
  secret: ${APP_JWT_SECRET}
  expiration: ${APP_JWT_EXPIRATION}

logging:
  level:
    org.springframework: debug
server:
  port: 8080
