spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${APP_MYSQL_HOST}/${APP_MYSQL_DB}
    username: ${APP_MYSQL_USERNAME}
    password: ${APP_MYSQL_PASSWORD}
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  cassandra:
    keyspace-name: lunchbunch
    contact-points: 127.0.0.1:9042
    local-datacenter: datacenter1

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}
  topic: ${REDIS_TOPIC}

jwt:
  secret: ${APP_JWT_SECRET}
  expiration: ${APP_JWT_EXPIRATION}

logging:
  level:
    org.springframework: debug
server:
  port: 8080
