spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${APP_MYSQL_HOST}/${APP_MYSQL_DB}
    username: ${APP_MYSQL_USERNAME}
    password: ${APP_MYSQL_PASSWORD}
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

jwt:
  secret: ${APP_JWT_SECRET}
  expiration: ${APP_JWT_EXPIRATION}

logging:
  level:
    org.springframework: debug